// <auto-generated />
using AgentSecure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgentSecure.Migrations
{
    [DbContext(typeof(AgentSecureDbContext))]
    partial class AgentSecureDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgentSecure.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CatName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CatName = "Theme Park"
                        },
                        new
                        {
                            Id = 2,
                            CatName = "Cruise"
                        },
                        new
                        {
                            Id = 3,
                            CatName = "Tour Operator"
                        },
                        new
                        {
                            Id = 4,
                            CatName = "Luxury Travel"
                        },
                        new
                        {
                            Id = 5,
                            CatName = "All-Inclusive"
                        },
                        new
                        {
                            Id = 6,
                            CatName = "Reseller"
                        });
                });

            modelBuilder.Entity("AgentSecure.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RegApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("TrainingComplete")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VendorId");

                    b.ToTable("Logins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice.j@viking.com",
                            Password = "Pass123!",
                            RegApproved = true,
                            TrainingComplete = true,
                            UserId = 1,
                            Username = "alice.viking",
                            VendorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "alice.s@sandals.com",
                            Password = "Tropic123!",
                            RegApproved = true,
                            TrainingComplete = false,
                            UserId = 1,
                            Username = "alice.sandals",
                            VendorId = 3
                        },
                        new
                        {
                            Id = 3,
                            Email = "alice.r@royal.com",
                            Password = "CruiseIt!",
                            RegApproved = false,
                            TrainingComplete = false,
                            UserId = 1,
                            Username = "alice.rccl",
                            VendorId = 5
                        },
                        new
                        {
                            Id = 4,
                            Email = "alice.a@applevacs.com",
                            Password = "BeachTime!",
                            RegApproved = true,
                            TrainingComplete = true,
                            UserId = 1,
                            Username = "alice.apple",
                            VendorId = 9
                        },
                        new
                        {
                            Id = 5,
                            Email = "alice.d@disney.com",
                            Password = "Magic123!",
                            RegApproved = true,
                            TrainingComplete = true,
                            UserId = 1,
                            Username = "alice.disney",
                            VendorId = 4
                        },
                        new
                        {
                            Id = 6,
                            Email = "bob.d@delta.com",
                            Password = "SkyHigh1!",
                            RegApproved = true,
                            TrainingComplete = false,
                            UserId = 2,
                            Username = "bob.delta",
                            VendorId = 2
                        },
                        new
                        {
                            Id = 7,
                            Email = "bob.g@globus.com",
                            Password = "Tours2024!",
                            RegApproved = false,
                            TrainingComplete = false,
                            UserId = 2,
                            Username = "bob.globus",
                            VendorId = 6
                        },
                        new
                        {
                            Id = 8,
                            Email = "bob.t@ti.com",
                            Password = "ResortLife!",
                            RegApproved = true,
                            TrainingComplete = true,
                            UserId = 2,
                            Username = "bob.ti",
                            VendorId = 7
                        },
                        new
                        {
                            Id = 9,
                            Email = "bob.e@expedia.com",
                            Password = "EasyBook!",
                            RegApproved = true,
                            TrainingComplete = false,
                            UserId = 2,
                            Username = "bob.expedia",
                            VendorId = 8
                        },
                        new
                        {
                            Id = 10,
                            Email = "bob.a@amr.com",
                            Password = "AMRsecure!",
                            RegApproved = true,
                            TrainingComplete = true,
                            UserId = 2,
                            Username = "bob.amresorts",
                            VendorId = 10
                        });
                });

            modelBuilder.Entity("AgentSecure.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Nashville",
                            Email = "alice.johnson@example.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            Phone = "555-123-4567",
                            State = "TN",
                            StreetAddress = "123 Elm Street",
                            Uid = "-Nabc123XYZ7890user1",
                            Zip = "37201"
                        },
                        new
                        {
                            Id = 2,
                            City = "Atlanta",
                            Email = "bob.martinez@example.com",
                            FirstName = "Bob",
                            LastName = "Martinez",
                            Phone = "555-987-6543",
                            State = "GA",
                            StreetAddress = "456 Oak Avenue",
                            Uid = "-Ndef456LMN4567user2",
                            Zip = "30301"
                        });
                });

            modelBuilder.Entity("AgentSecure.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Consortium")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LoginWebsite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Consortium = "",
                            Description = "Luxury river and ocean cruise line known for cultural experiences.",
                            LoginWebsite = "https://www.vikingtravelagents.com",
                            Name = "Viking Cruises",
                            Phone = "800-706-1483",
                            Website = "https://www.vikingcruises.com"
                        },
                        new
                        {
                            Id = 2,
                            Consortium = "VAX Vacation Access",
                            Description = "Air and hotel vacation packages powered by Delta Air Lines.",
                            LoginWebsite = "www.vaxvacationaccess.com",
                            Name = "Delta Vacations",
                            Phone = "800-727-1111",
                            Website = "https://www.delta.com/vacations"
                        },
                        new
                        {
                            Id = 3,
                            Consortium = "",
                            Description = "All-inclusive Caribbean resorts for couples.",
                            LoginWebsite = "https://taportal.sandals.com",
                            Name = "Sandals Resorts",
                            Phone = "888-726-3257",
                            Website = "https://www.sandals.com"
                        },
                        new
                        {
                            Id = 4,
                            Consortium = "",
                            Description = "Booking site and resources for Disney Destinations travel professionals.",
                            LoginWebsite = "https://www.disneytravelagents.com",
                            Name = "Disney Travel Agents",
                            Phone = "877-569-3276",
                            Website = "https://www.disneytravelagents.com"
                        },
                        new
                        {
                            Id = 5,
                            Consortium = "Cruising Power",
                            Description = "Popular cruise line with innovative ships and global destinations.",
                            LoginWebsite = "https://www.cruisingpower.com",
                            Name = "Royal Caribbean",
                            Phone = "800-327-2056",
                            Website = "https://www.royalcaribbean.com"
                        },
                        new
                        {
                            Id = 6,
                            Consortium = "",
                            Description = "Tour operator offering guided land tours and independent travel.",
                            LoginWebsite = "https://www.globusfamily.com/TravelAgents",
                            Name = "Globus Family of Brands",
                            Phone = "866-755-8581",
                            Website = "https://www.globusjourneys.com"
                        },
                        new
                        {
                            Id = 7,
                            Consortium = "",
                            Description = "Luxury vacation wholesaler with access to top resorts worldwide.",
                            LoginWebsite = "https://www.vaxvacationaccess.com",
                            Name = "Travel Impressions",
                            Phone = "800-284-0044",
                            Website = "https://www.travelimpressions.com"
                        },
                        new
                        {
                            Id = 8,
                            Consortium = "",
                            Description = "Travel agent affiliate program offering hotels, flights, and packages.",
                            LoginWebsite = "https://www.expediataap.com",
                            Name = "Expedia TAAP",
                            Phone = "866-310-5768",
                            Website = "https://www.expedia.com"
                        },
                        new
                        {
                            Id = 9,
                            Consortium = "VAX Vacation Access",
                            Description = "U.S. tour operator known for beach vacations and charter flights.",
                            LoginWebsite = "https://www.vaxvacationaccess.com",
                            Name = "Apple Vacations",
                            Phone = "800-517-2000",
                            Website = "https://www.applevacations.com"
                        },
                        new
                        {
                            Id = 10,
                            Consortium = "",
                            Description = "Collection of luxury resort brands in Mexico and the Caribbean.",
                            LoginWebsite = "https://www.amragents.com",
                            Name = "AmResorts",
                            Phone = "866-847-8184",
                            Website = "https://www.amrcollection.com"
                        });
                });

            modelBuilder.Entity("AgentSecure.Models.VendorCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("VendorId");

                    b.ToTable("VendorCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            VendorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 4,
                            VendorId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            VendorId = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            VendorId = 3
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            VendorId = 3
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            VendorId = 4
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            VendorId = 5
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            VendorId = 6
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 6,
                            VendorId = 7
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            VendorId = 7
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            VendorId = 8
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            VendorId = 9
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 6,
                            VendorId = 10
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            VendorId = 10
                        });
                });

            modelBuilder.Entity("AgentSecure.Models.Login", b =>
                {
                    b.HasOne("AgentSecure.Models.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgentSecure.Models.Vendor", "Vendor")
                        .WithMany("Logins")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("AgentSecure.Models.VendorCategory", b =>
                {
                    b.HasOne("AgentSecure.Models.Category", "Category")
                        .WithMany("VendorCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgentSecure.Models.Vendor", "Vendor")
                        .WithMany("VendorCategories")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("AgentSecure.Models.Category", b =>
                {
                    b.Navigation("VendorCategories");
                });

            modelBuilder.Entity("AgentSecure.Models.User", b =>
                {
                    b.Navigation("Logins");
                });

            modelBuilder.Entity("AgentSecure.Models.Vendor", b =>
                {
                    b.Navigation("Logins");

                    b.Navigation("VendorCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
